### ISSUE TITLE
Change the data returned

### ISSUE THREAD

**Issue by Lioness100** [notkyoyo/anime-facts#5]
The `getFact()` function returns an object containing the properties `_id`, `tags`, and `fact`, although `fact` is the only one that makes sense in context. I think we should change the function to just return the `fact` string.

```js
await getFact(); // 'Anime is not synonymous...'
```

We could also implement the ability to put query parameters as function parameters. For example:

```js
await getFact({ 
  tags: ['pokemon'], 
  grouped: true, /* tags.join(grouped ? ',' : '|') */
  maxLength: 10,
  minLength: 5,
});
```

**Comment by notkyoyo** [comment]
Well, yeah we could do that. But, for now, I'm super busy working on some other projects, so can't give an ETA.

**Comment by Lioness100** [comment]
I could create a PR 🙂🍿

**Comment by notkyoyo** [comment]
Feel free to do so, however, I still prefer getting the `_id`(just in case for a report, if there's any typo or anything on the fact).

**Comment by Lioness100** [comment]
Fair enough

**Comment by notkyoyo** [comment]
Oh, forgot to mention. The API does support queries, but there isn't any fact, that has tags on them. Probably I've to update the data as well if you're planning to make a PR.

**Comment by notkyoyo** [comment]
#6
